### ISSUE TITLE
make h5py/HDF5 an optional dependency

### ISSUE THREAD

**Issue by jairideout** [biocore/biom-format#288]
When running `print_qiime_config.py` against the latest dev versions of QIIME and biom-format:

``` bash
$ print_qiime_config.py 
Traceback (most recent call last):
  File "/home/jrideout/.virtualenvs/qiime/qiime/scripts/print_qiime_config.py", line 58, in <module>
    raise ImportError("%s\n%s" % (e, core_dependency_missing_msg))
ImportError: No module named h5py
See the QIIME Installation Guide: http://qiime.org/install/install.html
```

It'd be great to make this project not require h5py/HDF5 unless trying to read/write those types of files, as not all users will have access to these libraries.

**Comment by emilianaromagnoli** [comment]
I have this problems
I need help

**Comment by emilianaromagnoli** [comment]
cbp@ARSILPE14310102[app-deploy-qiime-1.5.0]  qiime > print_qiime_config_all -tf
Traceback (most recent call last):
  File "/usr/local/bin/print_qiime_config.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.0', 'print_qiime_config.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 698, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1616, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/qiime-1.9.0-py2.7.egg/EGG-INFO/scripts/print_qiime_config.py", line 57, in <module>
    raise ImportError("%s\n%s" % (e, core_dependency_missing_msg))
ImportError: cannot import name HAVE_H5PY
See the QIIME Installation Guide: http://qiime.org/install/install.html
