### ISSUE TITLE
biom convert is missing a switch to force overwrite of existing output

### ISSUE THREAD

**Issue by maasha** [biocore/biom-format#557]
This is biom-format==2.1

```
$ biom convert -i otu.tab -o otu.json --table-type="OTU table" --to-json
/usr/local/lib/python2.7/site-packages/biom/util.py:30: UserWarning: h5py is not available
  warn("h5py is not available")
Traceback (most recent call last):
  File "/usr/local/bin/pyqi", line 184, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/usr/local/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/usr/local/lib/python2.7/site-packages/pyqi/core/interface.py", line 41, in __call__
    return self._output_handler(cmd_result)
  File "/usr/local/lib/python2.7/site-packages/pyqi/core/interfaces/optparse/__init__.py", line 250, in _output_handler
    opt_value)
  File "/usr/local/lib/python2.7/site-packages/biom/interfaces/optparse/output_handler.py", line 59, in write_biom_table
    raise IOError("Output path '%s' already exists." % option_value)
IOError: Output path 'otu.json' already exists.
```

**Comment by jairideout** [comment]
Fixed in #668.
