### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by seangibbons** [biocore/biom-format#579]
Hey all,

Probably something dumb on my part, but I'm getting an error when I try to install the development version:

```
nsit-dhcp-205-208-076-111:~ seanmgibbons$ git clone git://github.com/biocore/biom-format.git
nsit-dhcp-205-208-076-111:~ seanmgibbons$ cd biom-format/
nsit-dhcp-205-208-076-111:biom-format seanmgibbons$ sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to biom_format.egg-info/requires.txt
writing biom_format.egg-info/PKG-INFO
writing top-level names to biom_format.egg-info/top_level.txt
writing dependency_links to biom_format.egg-info/dependency_links.txt
reading manifest file 'biom_format.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '.git' found anywhere in distribution
writing manifest file 'biom_format.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-x86_64/egg
running install_lib
running build_py
running build_ext
sh: line 1: 51970 Segmentation fault: 11  'gcc' --version 2> /dev/null > '/tmp/tmpKs3VBX'
Traceback (most recent call last):
  File "setup.py", line 111, in <module>
    classifiers=classifiers
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/seanmgibbons/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/Users/seanmgibbons/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/install.py", line 93, in do_egg_install
    self.run_command('bdist_egg')
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/seanmgibbons/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/bdist_egg.py", line 179, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/seanmgibbons/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/bdist_egg.py", line 166, in call_command
    self.run_command(cmdname)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/seanmgibbons/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/install_lib.py", line 20, in run
    self.build()
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/seanmgibbons/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/distribute-0.6.19-py2.7.egg/setuptools/command/build_ext.py", line 46, in run
    _build_ext.run(self)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/command/build_ext.py", line 307, in run
    customize_compiler(self.compiler)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/sysconfig.py", line 181, in customize_compiler
    _osx_support.customize_compiler(_config_vars)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/_osx_support.py", line 418, in customize_compiler
    _find_appropriate_compiler(_config_vars)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/_osx_support.py", line 185, in _find_appropriate_compiler
    if 'llvm-gcc' in data:
TypeError: argument of type 'NoneType' is not iterable
```

-sean

**Comment by Jorge-C** [comment]
Having a look at the Python code that raises the TypeError, maybe it's unable to find a compiler?

Not really familiar with the OSX stack, but do you have e.g. xcode installed? It should be possible to get a minimal build environment running `xcode-select --install`.

**Comment by seangibbons** [comment]
Yep, I have xcode installed:

seangibmacbook2:~ seanmgibbons$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates

This may be a Canopy issue. I've had a few problems in the past with python looking in the wrong place.

May also be due to a recent upgrade to OSX10.10?

**Comment by ElDeveloper** [comment]
If you recently upgraded to 10.10, I would update the command-line tools and try again. Xcode > Open Developer Tools > More Developer Tools.

**Comment by wasade** [comment]
@ElDeveloper recommending More Developer [Tools]...

**Comment by ElDeveloper** [comment]
Classic @ElDeveloper ... :neckbeard:

**Comment by seangibbons** [comment]
yup, that seems to be the problem! Downloading the new developer tools now. I'll get back to you if this doesn't resolve things. thanks!

**Comment by ElDeveloper** [comment]
This may be a canopy-only issue (perhaps you need to update it?), maybe it would be worthwhile trying anaconda.

Yoshiki Vázquez-Baeza

**Comment by seangibbons** [comment]
that is entirely possible. my canopy install is up to date. thanks for the help, I'll keep digging

**Comment by ElDeveloper** [comment]
I don't remember this off the top of my head but I think there's a way
to temporarily deactivate canopy. If this is possible, then I would
suggest trying to build (python setup.py build) biom with your system's
python and see if the problem is resolved, if so then canopy might be
the culprit.

**Comment by Jorge-C** [comment]
Hey, I took another stab at this and the issue is a bug in Python<=2.7.6 (issue [#21311](http://bugs.python.org/issue21311)). Since canopy only seems to provide Python 2.7.6, I'd use instead the anaconda distribution.

**Comment by ElDeveloper** [comment]
Thanks for looking into this, @seangibbons, hopefully this helps!

**Comment by seangibbons** [comment]
ok, good to know! thanks all!

**Comment by seangibbons** [comment]
Yep, that was the issue. I switched to anaconda, and the install finished without any errors. Thanks again!
