### ISSUE TITLE
biom summarize-table does not pipe well

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#598]
See below

```bash
$ biom summarize-table --version
Version: biom summarize-table 2.1.2
$ biom summarize-table -i AG_100nt_even10k.biom | head -n 1
Num samples: 3011
Traceback (most recent call last):
  File "/Users/mcdonadt/.virtualenvs/python27/bin/pyqi", line 177, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/Users/mcdonadt/ResearchWork/software/pyqi/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/Users/mcdonadt/ResearchWork/software/pyqi/pyqi/core/interface.py", line 41, in __call__
    return self._output_handler(cmd_result)
  File "/Users/mcdonadt/ResearchWork/software/pyqi/pyqi/core/interfaces/optparse/__init__.py", line 250, in _output_handler
    opt_value)
  File "/Users/mcdonadt/ResearchWork/software/pyqi/pyqi/core/interfaces/optparse/output_handler.py", line 95, in write_or_print_list_of_strings
    print_list_of_strings(result_key, data, option_value)
  File "/Users/mcdonadt/ResearchWork/software/pyqi/pyqi/core/interfaces/optparse/output_handler.py", line 68, in print_list_of_strings
    print(line)
IOError: [Errno 32] Broken pipe
```

**Comment by wasade** [comment]
See [here](http://newbebweb.blogspot.com/2012/02/python-head-ioerror-errno-32-broken.html) for a likely solution
