### ISSUE TITLE
biom.exception.BiomParseException: First column values are not unique! Cannot be ids.

### ISSUE THREAD

**Issue by RvV1979** [biocore/biom-format#643]
Hi all, 

I am running biom add-metadata as part of a 16s amplicon analysis pipeline and I am getting the following error:
biom.exception.BiomParseException: First column values are not unique! Cannot be ids.
I checked the sample-metadata file and the data seem to be unique... Does anyone know what may be going wrong? 

Thanks!

```
Traceback (most recent call last):
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/bin/pyqi", line 4, in <module>
    __import__('pkg_resources').run_script('pyqi==0.3.2', 'pyqi')
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 735, in run_script
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/setuptools-17.1.1-py2.7.egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/EGG-INFO/scripts/pyqi", line 184, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/interface.py", line 39, in __call__
    cmd_result = self.CmdInstance(**cmd_input)
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/command.py", line 137, in __call__
    result = self.run(**kwargs)
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/biom_format-2.1.2-py2.7-linux-x86_64.egg/biom/commands/metadata_adder.py", line 129, in run
    header=observation_header)
  File "/home/robin/miniconda/envs/qiime190rc2-rhl6/lib/python2.7/site-packages/biom_format-2.1.2-py2.7-linux-x86_64.egg/biom/parse.py", line 430, in from_file
    raise BiomParseException("First column values are not unique! "
biom.exception.BiomParseException: First column values are not unique! Cannot be ids.
(qiime190rc2-rhl6)robin@workhorse01:~/Documents/16S_amplicon_analysis/WUR_XU/analysis$ head ../data/metadata.csv
#SampleID   environment habitat
Rhizo-Col-1 arabidopsis rhizo
Rhizo-Col-2 arabidopsis rhizo
Rhizo-Col-3 arabidopsis rhizo
Rhizo-MO-1  arabidopsis rhizo
Rhizo-MO-2  arabidopsis rhizo
Rhizo-MO-3  arabidopsis rhizo
Rhizo-SMB-1 arabidopsis rhizo
Rhizo-SMB-2 arabidopsis rhizo
Rhizo-SBB-1 arabidopsis rhizo
(qiime190rc2-rhl6)robin@workhorse01:~/Documents/16S_amplicon_analysis/WUR_XU/analysis$ wc -l ../data/metadata.csv
35 ../data/metadata.csv
(qiime190rc2-rhl6)robin@workhorse01:~/Documents/16S_amplicon_analysis/WUR_XU/analysis$ cut -f 1 ../data/metadata.csv |uniq -|wc -l
35
```

**Comment by wasade** [comment]
Sorry for such a delayed response on this. Do you recall if you were able to resolve the problem? I haven't seen this in other situations, so I'm not yet sure if this is or isn't a bug.

**Comment by RvV1979** [comment]
Hi Daniel, I think this was resolved. Thanks
Op za 5 nov. 2016 om 21:11 schreef Daniel McDonald <notifications@github.com

**Comment by wasade** [comment]
Excellent, thanks
