### ISSUE TITLE
biom add-metadata fails with test data

### ISSUE THREAD

**Issue by johnchase** [biocore/biom-format#695]
Running biom add-metadata with the biom test data fails. I have been using other scripts in biom with no issues

``` bash
$ biom add-metadata -i min_sparse_otu_table.biom -o table.w_omd.biom --observation-metadata-fp obs_md.txt --observation-header OTUID,taxonomy
Traceback (most recent call last):
  File "/Users/jc33/miniconda3/envs/biom-test/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/biom/cli/metadata_adder.py", line 114, in add_metadata
    write_biom_table(result, fmt, output_fp)
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/biom/cli/util.py", line 35, in write_biom_table
    table.to_hdf5(f, biom.parse.generatedby())
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/biom/table.py", line 3605, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/biom/table.py", line 3577, in axis_dump
    formatter[category](grp, category, md, compression)
  File "/Users/jc33/miniconda3/envs/biom-test/lib/python2.7/site-packages/biom/table.py", line 277, in vlen_list_of_str_formatter
    data[i, :len(value)] = [v.encode('utf8') for v in value]
TypeError: iteration over a 0-d array
```

I'm using:
Python (2.7.11)
biom-format (2.1.5)
click (6.6)
future (0.15.2)
h5py (2.6.0)
numpy (1.11.0)

**Comment by wasade** [comment]
Is obs_md.txt in the repository? (On phone ATM...)

**Comment by johnchase** [comment]
Yes, 
biom-format/examples/obs_md.txt

**Comment by wasade** [comment]
Okay, thank you. Will check soon

**Comment by wasade** [comment]
@johnchase, first, it looks like only `--observation-header taxonomy` is necessary. However, I'm unable to get it to work. Digging in, and tossing in debugging print statements, it appears that `MetadataMap.from_file` is not pulling the taxonomy out. Specifically, it seems as though the `header` and `vals` `list`s are out of sync where index `header` is "left" shifted ([here](https://github.com/biocore/biom-format/blob/master/biom/parse.py#L540)).

@jairideout, any thoughts on this by chance? Figured I'd ping you first before going too deep on this, although I realize it's probably been a bit since you've seen the code

**Comment by jairideout** [comment]
It's been a long time since I've seen that code, but I think it was ported from QIIME. AFAIK it used to work, so something must have broken during one of the biom rewrites?

**Comment by johnchase** [comment]
@lkursell pointed out that adding the `--sc-separated taxonomy` flag to the command will make the orignal command succesful

so 
```bash
$ biom add-metadata -i min_sparse_otu_table.biom -o table.w_omd.biom --observation-metadata-fp obs_md.txt --observation-header OTUID,taxonomy --sc-separated taxonomy
```
works as expected. The original command I was running was copied directly from the documentation. Does this parameter need to be required, or at least should the documentation be updated to include it and note that the command will fail without it?

**Comment by wasade** [comment]
It isn't required as it depends on the metadata being added in. Would you like to issue a PR to adjust the documentation by chance?

**Comment by johnchase** [comment]
@wasade should the documentation state that the `--sc-separated taxonomy` is required?

**Comment by wasade** [comment]
@johnchase, would you be able to issue a PR on this by chance?
