### ISSUE TITLE
Unable to support list of int in metadata with format 2.1

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#700]
Originally reported [here](https://groups.google.com/forum/#!topic/qiime-forum/pKLP_6a6Mns)

``` python
> biom.example_table.add_metadata({'O1': {'foo': [1, 2, 3]}, 'O2': {'foo': [5, 6, 7]}}, axis='observation')

> biom.example_table.metadata(axis='observation')
Out[4]:
(defaultdict(<function biom.table.<lambda>>,
             {'foo': [1, 2, 3], 'taxonomy': ['Bacteria', 'Firmicutes']}),
 defaultdict(<function biom.table.<lambda>>,
             {'foo': [5, 6, 7], 'taxonomy': ['Bacteria', 'Bacteroidetes']}))

> import h5py

> f = h5py.File('footest')

> biom.example_table.to_hdf5(f, 'asd')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-640fdd4ae14a> in <module>()
----> 1 biom.example_table.to_hdf5(f, 'asd')

/lib/python2.7/site-packages/biom/table.pyc in to_hdf5(self, h5grp, generated_by, compress, format_fs)
   3603                   self.ids(axis='observation'),
   3604                   self.metadata(axis='observation'),
-> 3605                   self.group_metadata(axis='observation'), 'csr', compression)
   3606         axis_dump(h5grp.create_group('sample'), self.ids(),
   3607                   self.metadata(), self.group_metadata(), 'csc', compression)

/lib/python2.7/site-packages/biom/table.pyc in axis_dump(grp, ids, md, group_md, order, compression)
   3575                     # Create the dataset for the current category,
   3576                     # putting values in id order
-> 3577                     formatter[category](grp, category, md, compression)
   3578
   3579             # Create the group for the group metadata

/lib/python2.7/site-packages/biom/table.pyc in general_formatter(grp, header, md, compression)
    244             'metadata/%s' % header, shape=(len(md),),
    245             data=[m[header] for m in md],
--> 246             compression=compression)
    247
    248

/lib/python2.7/site-packages/h5py/_hl/group.pyc in create_dataset(self, name, shape, dtype, data, **kwds)
    101         """
    102         with phil:
--> 103             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    104             dset = dataset.Dataset(dsid)
    105             if name is not None:
/lib/python2.7/site-packages/h5py/_hl/dataset.pyc in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     64         shape = tuple(shape)
     65         if data is not None and (numpy.product(shape) != numpy.product(data.shape)):
---> 66             raise ValueError("Shape tuple is incompatible with data")
     67
     68     tmp_shape = maxshape if maxshape is not None else shape

ValueError: Shape tuple is incompatible with data
```

**Comment by wasade** [comment]
The scope of this is really in a rewrite of the parsers and formatters for biom 2.1.0 unfortunately. I do not believe this is a situation normally encountered as I'm not aware of any heavy uses of the metadata support with biom other than taxonomy and KEGG pathways. As such, I'm moving this to milestone 2.2 as this would be much easier to do via a `DataFrame` (e.g., #719)

**Comment by ElDeveloper** [comment]
I am seeing a similar problem when I try to use the `biom add-metadata` command to add the taxonomy information to a QIIME2-produced table, the taxonomy is also QIIME2-produced.

```
Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/cli/metadata_adder.py", line 114, in add_metadata
    write_biom_table(result, fmt, output_fp)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/cli/util.py", line 35, in write_biom_table
    table.to_hdf5(f, biom.parse.generatedby())
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py", line 3605, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py", line 3577, in axis_dump
    formatter[category](grp, category, md, compression)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py", line 246, in general_formatter
    compression=compression)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/h5py/_hl/group.py", line 105, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 72, in make_new_dset
    raise ValueError("Shape tuple is incompatible with data")
ValueError: Shape tuple is incompatible with data
```

The command I am using is:

```bash
biom add-metadata \
--observation-metadata-fp taxonomy.tsv \
-i feature-table.biom \
-o otu-table.taxonomy.biom \
--sc-separated Taxon
```

**Comment by wasade** [comment]
This has to do with the confusing construction of the add-metadata command.
I believe you need to set the header info (if not present) and also specify
the column or columns to add

On Feb 22, 2017 07:31, "Yoshiki Vázquez Baeza" <notifications@github.com>
wrote:

I am seeing a similar problem when I try to use the biom add-metadata
command to add the taxonomy information to a QIIME2-produced table, the
taxonomy is also QIIME2-produced.

Traceback (most recent call last):
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/bin/biom",
line 11, in <module>
    sys.exit(cli())
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py",
line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py",
line 697, in main
    rv = self.invoke(ctx)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py",
line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py",
line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/click/core.py",
line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/cli/metadata_adder.py",
line 114, in add_metadata
    write_biom_table(result, fmt, output_fp)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/cli/util.py",
line 35, in write_biom_table
    table.to_hdf5(f, biom.parse.generatedby())
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py",
line 3605, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py",
line 3577, in axis_dump
    formatter[category](grp, category, md, compression)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py",
line 246, in general_formatter
    compression=compression)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/h5py/_hl/group.py",
line 105, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/h5py/_hl/dataset.py",
line 72, in make_new_dset
    raise ValueError("Shape tuple is incompatible with data")
ValueError: Shape tuple is incompatible with data

The command I am using is:

biom add-metadata \
--observation-metadata-fp taxonomy.tsv \
-i feature-table.biom \
-o otu-table.taxonomy.biom \
--sc-separated Taxon

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/biocore/biom-format/issues/700#issuecomment-281703217>,
or mute the thread

**Comment by ElDeveloper** [comment]
Interesting, that still raised the same error:

```bash
biom add-metadata \
--observation-metadata-fp taxonomy.tsv \
-i feature-table.biom \
-o otu-table.taxonomy.biom \
--sc-separated Taxon --observation-header OTUID,Taxon 
```

When I just add the metadata without using the `--sc-separated Taxon` option and without `--observation-header OTUID,Taxon` the command works just fine except the taxonomy string is not stored as a list of strings.

**Comment by ElDeveloper** [comment]
Just in case, this solved my problem:

```python
from biom import load_table
import pandas as pd

bt = load_table('feature-table.biom')
df = pd.read_csv('taxonomy.tsv',
                 sep='\t', converters={'Taxon': lambda x: x.split('; ')}, dtype='str',
                 keep_default_na=False, na_values=[])
df.set_index("#OTUID", inplace=True)
df.drop(['Confidence'], axis=1, inplace=True)

bt.add_metadata(df.to_dict('index'), 'observation')
```

**Comment by ElDeveloper** [comment]
^ that didn't actually solve my problem as I can't serialize the table to HDF5.

**Comment by wasade** [comment]
I don't understand the HDF5 comment... does `bt.to_hdf5` not work? Just need to pass an HDF5 handle (e.g., `h5py.File`)

Can you email me the table/taxonomy (or paths I can use)?

**Comment by ElDeveloper** [comment]
Apologies for the cryptic reply, when I tried to serialize, I wasn't able to, the same exception came up:

```python
ValueError                                Traceback (most recent call last)
<ipython-input-28-43649a51de33> in <module>()
      9 
     10 with biom_open('qiime2-data/otu-table.taxonomy.biom', 'w') as fh:
---> 11     bt.to_hdf5(fh, 'Add taxonomy information to the table.')

/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py in to_hdf5(self, h5grp, generated_by, compress, format_fs)
   3603                   self.ids(axis='observation'),
   3604                   self.metadata(axis='observation'),
-> 3605                   self.group_metadata(axis='observation'), 'csr', compression)
   3606         axis_dump(h5grp.create_group('sample'), self.ids(),
   3607                   self.metadata(), self.group_metadata(), 'csc', compression)

/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py in axis_dump(grp, ids, md, group_md, order, compression)
   3575                     # Create the dataset for the current category,
   3576                     # putting values in id order
-> 3577                     formatter[category](grp, category, md, compression)
   3578 
   3579             # Create the group for the group metadata

/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/biom/table.py in general_formatter(grp, header, md, compression)
    244             'metadata/%s' % header, shape=(len(md),),
    245             data=[m[header] for m in md],
--> 246             compression=compression)
    247 
    248 

/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/h5py/_hl/group.py in create_dataset(self, name, shape, dtype, data, **kwds)
    103         """
    104         with phil:
--> 105             dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
    106             dset = dataset.Dataset(dsid)
    107             if name is not None:

/Users/yoshikivazquezbaeza/miniconda/envs/herfarth-ccfa-py3/lib/python3.5/site-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times)
     70         shape = tuple(shape)
     71         if data is not None and (numpy.product(shape) != numpy.product(data.shape)):
---> 72             raise ValueError("Shape tuple is incompatible with data")
     73 
     74     tmp_shape = maxshape if maxshape is not None else shape

ValueError: Shape tuple is incompatible with data
```

I was serializing like this:

```python
with biom_open('table.taxonomy.biom', 'w') as fh:
    bt.to_hdf5(fh, 'Add taxonomy information to the table.')
```

**Comment by wasade** [comment]
```bash
$  biom add-metadata --observation-metadata-fp taxonomy.tsv -i feature-table.biom -o otu-table.taxonomy.biom --sc-separated Taxon --observation-header OTUID,Taxonomy,Confidence
```

The issue is that the column name needed to be relabeled. The voodoo behind the scenes is that, on write, `Table` interprets the metadata key "taxonomy" as a special formatter, and does not understand "Taxon"

**Comment by ElDeveloper** [comment]
Thanks @wasade, but I don't believe this solves the problem, as I see the taxonomy string just as that, instead of as a list of strings, see the repr of the metadata after I run the command you suggested above:

```python
>>> bt = load_table('qiime2-data/otu-table.taxonomy.biom')
>>> bt.metadata(axis='observation')[0]

defaultdict(<function biom.table.Table._cast_metadata.<locals>.cast_metadata.<locals>.<lambda>>,
            {'Confidence': '-1.0',
             'Taxonomy': 'k__Bacteria; p__Bacteroidetes; c__Bacteroidia; o__Bacteroidales; f__Bacteroidaceae; g__Bacteroides; s__'})
```

The taxonomy metadata should be broken-up into a list, right?

**Comment by wasade** [comment]
The `--sc-separated` needs to reflect the `--observation-header` argument, and both should indicate `taxonomy` lowercase:

```python
$ biom add-metadata --observation-metadata-fp taxonomy.tsv -i feature-table.biom -o otu-table.taxonomy.biom --sc-separated taxonomy --observation-header OTUID,taxonomy,Confidence
$ ipython

In [1]: import biom

In [2]: t = biom.load_table('otu-table.taxonomy.biom')

In [3]: t.metadata(axis='observation')[0]
Out[3]:
defaultdict(<function biom.table.Table._cast_metadata.<locals>.cast_metadata.<locals>.<lambda>>,
            {'Confidence': '-1.0',
             'taxonomy': ['k__Bacteria',
              'p__Bacteroidetes',
              'c__Bacteroidia',
              'o__Bacteroidales',
              'f__Bacteroidaceae',
              'g__Bacteroides',
              's__']})
```

**Comment by ElDeveloper** [comment]
Great, this solves it, thanks so much!

Yoshiki.
