### ISSUE TITLE
update future package 

### ISSUE THREAD

**Issue by HannesHolste** [biocore/biom-format#725]
Using a pip installation of biom-format (v 2.1.5) with future package v 0.15.2 throws an error:
```
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Anaconda is brought to you by Continuum Analytics.
>>> import biom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hannes/miniconda2/envs/mdsapprox/lib/python2.7/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/Users/hannes/miniconda2/envs/mdsapprox/lib/python2.7/site-packages/biom/table.py", line 188, in <module>
    from future.utils import string_types
ImportError: cannot import name string_types
```

This can be resolved by upgrading future to v0.16.0. The dependency of biom-format in setup.py still lists future >= 0.15.0

**Comment by wasade** [comment]
resolved by #726
