### ISSUE TITLE
Conversion to hdf5 from json_biom

### ISSUE THREAD

**Issue by maexlich** [biocore/biom-format#745]
There seems to be an error when converting json biom files (created by MetaPhlAn2) into the hdf5 format.
Setup: python 3.5 on Linux workstation
Repository version: 32182413626ee729507a52cb2d33708978713129 (most recent at time of writing)
Example:
```
somefile.biom.json:
{
  "id": "MetaPhlAn2_Analysis",
  "format": "Biological Observation Matrix 1.0.0",
  "format_url": "http:\/\/biom-format.org",
  "generated_by": "MetaPhlAn2",
  "date": "2017-04-13T20:02:41.706093",
  "matrix_element_type": "float",
  "shape": [
    1,
    1
  ],
  "type": null,
  "matrix_type": "sparse",
  "data": [
    [
      0,
      0,
      100
    ]
  ],
  "rows": [
    {
      "id": 468,
      "metadata": {
        "taxonomy": [
          "k__Bacteria",
          "p__Actinobacteria",
          "c__Actinobacteria",
          "o__Bifidobacteriales",
          "f__Bifidobacteriaceae",
          "g__Bifidobacterium",
          "s__Bifidobacterium_breve"
        ]
      }
    }
  ],
  "columns": [
    {
      "id": "Metaphlan2_Analysis",
      "metadata": null
    }
  ]
}

Command:
biom convert -i somefile.biom.json -o somefile.biom --to-hdf5
Traceback (most recent call last):
  File "***/bin/biom", line 11, in <module>
    sys.exit(cli())
  File "***/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "***/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "***/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "***/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "***/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "***/lib/python3.5/site-packages/biom/cli/table_converter.py", line 129, in convert
    table_type, process_obs_metadata, tsv_metadata_formatter)
  File "***/lib/python3.5/site-packages/biom/cli/table_converter.py", line 207, in _convert
    write_biom_table(result, fmt, output_filepath)
  File "***/lib/python3.5/site-packages/biom/cli/util.py", line 35, in write_biom_table
    table.to_hdf5(f, biom.parse.generatedby())
  File "***/lib/python3.5/site-packages/biom/table.py", line 4119, in to_hdf5
    self.group_metadata(axis='observation'), 'csr', compression)
  File "***/lib/python3.5/site-packages/biom/table.py", line 4071, in axis_dump
    data=[i.encode('utf8') for i in ids],
  File "***/lib/python3.5/site-packages/biom/table.py", line 4071, in <listcomp>
    data=[i.encode('utf8') for i in ids],
AttributeError: 'int' object has no attribute 'encode'
```

It seems as if the to_hdf5 function assumes the ids to be strings, while MetaPhlAn encodes them as integer types in the json file.

**Comment by wasade** [comment]
Metaphlan is writing invalid biom tables as the IDs are [defined](http://biom-format.org/documentation/format_versions/biom-1.0.html) as strings. Can you open an issue with the Metaphlan devs?
