### ISSUE TITLE
convert txt. into biom file 

### ISSUE THREAD

**Issue by Acetylcholine88** [biocore/biom-format#763]
Can someone help?

Tried the following command:

biom convert -i OTU_original.txt -o OTU_original.biom --table-type "OTU table" --to-hdf5 --process-obs-metadata taxonomy

this is what I got:

biom convert: error: option -i: file does not exist: 'OTU.txt'

-bash-4.2$ biom convert -i OTU_original.txt -o OTU_original.biom --table-type "OTU table" --process-obs-metadata taxonomy

Traceback (most recent call last):

File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/bin/pyqi", line 4, in

__import__('pkg_resources').run_script('pyqi==0.3.2', 'pyqi')
File "build/bdist.linux-x86_64/egg/pkg_resources/init.py", line 738, in run_script

File "build/bdist.linux-x86_64/egg/pkg_resources/init.py", line 1499, in run_script

File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/EGG-INFO/scripts/pyqi", line 184, in

optparse_main(cmd_obj, argv[1:])
File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/interfaces/optparse/init.py", line 275, in optparse_main

result = optparse_cmd(local_argv[1:])
File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/interface.py", line 39, in call

cmd_result = self.CmdInstance(**cmd_input)
File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/pyqi-0.3.2-py2.7.egg/pyqi/core/command.py", line 137, in call

result = self.run(**kwargs)
File "/ycga-gpfs/apps/hpc/software/Python/2.7.13-foss-2016b/lib/python2.7/site-packages/biom/commands/table_converter.py", line 217, in run

raise CommandError(convert_error_msg)
pyqi.core.exception.CommandError: Input does not look like a classic table. Did you forget to specify that a classic table file should be created from a BIOM table file?

Help would be very much appreciated - I am super lost!

[OTU_original_MF_samples_v1v3_sorted_test.txt](https://github.com/biocore/biom-format/files/1411705/OTU_original_MF_samples_v1v3_sorted_test.txt)

**Comment by wasade** [comment]
Hi @Acetylcholine88, it looks like in the first error the file path specified did not exist? I'm less clear on the second error. 

From looking at the file, it appears to be missing the `#` mark. Specifically, the first row in the first column needs to be `#OTU ID"`. Once that's corrected, would you be able to try the following?

```bash
$ biom convert -i OTU_original_MF_samples_v1v3_sorted_test.txt -o OTU_original.biom --table-type "OTU table" --process-obs-metadata taxonomy
```

**Comment by Acetylcholine88** [comment]
-bash-4.2$ $ biom convert -i OTU_original_MF_samples_v1v3_sorted_test.txt -o OTU_original.biom --table-type "OTU table" --process-obs-metadata taxonomy
bash: $: command not found...

**Comment by Acetylcholine88** [comment]
I really don’t know what the issue is...

**Comment by wasade** [comment]
Can you remove the leading "$"? It just denotes a prompt

**Comment by Acetylcholine88** [comment]
-bash-4.2$ biom convert -i OTU_original_MF_samples_v1v3_sorted_test.txt -o OTU_original.biom --table-type "OTU table" --process-obs-metadata taxonomy
bash: biom: command not found...

**Comment by wasade** [comment]
It looks like biom is not installed. Are you using biom from a QIIME environment, and if so, does QIIME work (e.g., `print_qiime_config.py`)?

**Comment by smajor1** [comment]
I don't want to open a new issue for a similar command issue so I'll piggy back here a bit. 
I'm trying to convert a tab-delimited table to biom in the qiime environment.
```
biom convert -i filt-otu-tab.txt -o filt.biom --table-type="OTU table" --to-json
ValueError: column index exceeds matrix dimensions
```
I can't imagine anything is wrong with my table as I've not manipulated it directly.

**Comment by wasade** [comment]
@smajor1 , how was the table produced, and would it be possible to paste the full traceback?

**Comment by smajor1** [comment]
It was originally produces in QIIME, then moved to R for manipulation with phyloseq. I wrote the table as tsv/txt file which is in an identical format as QIIME to txt, but without the meta/observation data. 
`Traceback (most recent call last):
  File "/usr/local/bin/pyqi", line 184, in <module>
    optparse_main(cmd_obj, argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pyqi/core/interfaces/optparse/__init__.py", line 275, in optparse_main
    result = optparse_cmd(local_argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pyqi/core/interface.py", line 38, in __call__
    cmd_input = self._input_handler(in_, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyqi/core/interfaces/optparse/__init__.py", line 194, in _input_handler
    self._optparse_input[optparse_clean_name])
  File "/usr/local/lib/python2.7/dist-packages/biom/interfaces/optparse/input_handler.py", line 42, in load_biom_table
    return parse_biom_table(table_f)
  File "/usr/local/lib/python2.7/dist-packages/biom/parse.py", line 313, in parse_biom_table
    t = Table.from_tsv(fp, None, None, lambda x: x)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 3842, in from_tsv
    return Table(data, obs_ids, sample_ids, obs_metadata, sample_metadata)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 307, in __init__
    shape=shape)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 450, in _to_sparse
    mat = list_list_to_sparse(values, dtype, shape=shape)
  File "/usr/local/lib/python2.7/dist-packages/biom/table.py", line 4090, in list_list_to_sparse
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/coo.py", line 206, in __init__
    self._check()
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/coo.py", line 262, in _check
    raise ValueError('column index exceeds matrix dimensions')
ValueError: column index exceeds matrix dimensions
`
I actually just did some fiddling and it seems like QIIME/biom-format wants the OTU ID header "#OTU ID" in the Top left most cell... it actually looks like that's required for all header lines.

**Comment by wasade** [comment]
Can you send the following output, where "<your file>" is the file path to the file you'd like to convert?

```bash
$ cut -f 1,2,3,4,5 <your fille> | head -n 6
```

What that command will (should) do is grab the first 5 columns of the tab delimited file, and then retain the header and the first five rows.

**Comment by kathwhittey** [comment]
Hi Wasade, 

I am having the same issue trying to convert a .txt to .biom - I get the error ValueError: column index exceeds matrix dimensions. I have executed the script you've given above and it is correctly displaying the first 5 columns. What should I do next? 

#OTU ID P1.A1   P1.A10  P1.A11  P1.A2
1519    0       0       0       0
1817    0       0       0       0
1105    0       0       0       0
1094    0       0       0       0
586     0       0       0       0

**Comment by wasade** [comment]
Hi @kathwhittey,

I'm closing this issue as it appears stale. Can you open a new issue, and provide the commands used to attempt to perform the conversion?

Thanks,
Daniel
