### ISSUE TITLE
biom convert, numpy.dtype error

### ISSUE THREAD

**Issue by reikopm** [biocore/biom-format#782]
Apologies I am not familiar with python and I am just the user. Our IS department takes care of the installation of programs.

That being said, IS updated python and now I am receiving this error, see below. Previously the code worked. Our version of biom was downloaded in Dec 2015. I don't know how to find out the biom version.  IS said I needed to talk to you, the developer, about my problem.

Is there a more current version of biom that would work with python v2.7.5?

I don't know where to get help with this. If this is inappropriate please point me in the right direction.

Many thanks,
-Reiko

biom convert -i /home/mbonteam/MBARI/reiko/processed/m2w/12S/Analysis_20180726_1225/all_lib/OTUs_swarm/OTU_table.txt -o /home/mbonteam/MBARI/reiko/processed/m2w/12S/Analysis_20180726_1225/all_lib/Post_Blast_20180731_1652/MB_12S_NT_json.biom --table-type=OTU table --to-json
Traceback (most recent call last):
  File "/usr/bin/biom", line 9, in <module>
    load_entry_point('biom-format==2.1.5', 'console_scripts', 'biom')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib64/python2.7/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/usr/lib64/python2.7/site-packages/biom/table.py", line 190, in <module>
    from biom.util import (get_biom_format_version_string,
  File "/usr/lib64/python2.7/site-packages/biom/util.py", line 24, in <module>
    import h5py
  File "/usr/lib64/python2.7/site-packages/h5py/__init__.py", line 23, in <module>
    from . import _conv
  File "h5py/h5t.pxd", line 14, in init h5py._conv (/tmp/pip-build-QzhfDk/h5py/h5py/_conv.c:7359)
  File "h5py/numpy.pxd", line 66, in init h5py.h5t (/tmp/pip-build-QzhfDk/h5py/h5py/h5t.c:20455)
ValueError: numpy.dtype has the wrong size, try recompiling
biom add-metadata -i /home/mbonteam/MBARI/reiko/processed/m2w/12S/Analysis_20180726_1225/all_lib/Post_Blast_20180731_1652/MB_12S_NT_json.biom -o /home/mbonteam/MBARI/reiko/processed/m2w/12S/Analysis_20180726_1225/all_lib/Post_Blast_20180731_1652/MB_12S_NT_json_obs.biom --observation-metadata-fp /home/mbonteam/MBARI/reiko/processed/m2w/12S/Analysis_20180726_1225/all_lib/Post_Blast_20180731_1652/obs_md_all.txt --output-as-json
Traceback (most recent call last):
  File "/usr/bin/biom", line 9, in <module>
    load_entry_point('biom-format==2.1.5', 'console_scripts', 'biom')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib64/python2.7/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/usr/lib64/python2.7/site-packages/biom/table.py", line 190, in <module>
    from biom.util import (get_biom_format_version_string,
  File "/usr/lib64/python2.7/site-packages/biom/util.py", line 24, in <module>
    import h5py
  File "/usr/lib64/python2.7/site-packages/h5py/__init__.py", line 23, in <module>
    from . import _conv
  File "h5py/h5t.pxd", line 14, in init h5py._conv (/tmp/pip-build-QzhfDk/h5py/h5py/_conv.c:7359)
  File "h5py/numpy.pxd", line 66, in init h5py.h5t (/tmp/pip-build-QzhfDk/h5py/h5py/h5t.c:20455)
ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by wasade** [comment]
Hi @reikopm, it looks like your build of `h5py` is in consistent with your numpy library; this is not an issue with `biom`. My best guess is the IS department only partially updated the environments. You may want to ask them to uninstall `h5py` and reinstall it. 

If you want to give your IS department something that they can use as an example of the problem, I'm willing to bet the following command will trigger the issue:

```python
$ python -c "import h5py"
```

Please let me know how it goes. I'm closing this issue for now because it's not actually with biom, but I do want to make sure you're able to get your work done.

As an alternative, you could [install](https://docs.qiime2.org/2018.6/install/) QIIME 2 in your home directory (without asking your IS department). QIIME 2 also has a strong community for [help](https://forum.qiime2.org/) if you run into issues.
