### ISSUE TITLE
Unexpected error when subsampling metabolomics dataset

### ISSUE THREAD

**Issue by rhmills** [biocore/biom-format#806]
When trying to perform Qiime2's diversity core-metrics command on metabolomics data, I ran into an issue occurring in the rarefaction step. I was able to reproduce this with the `qiime feature-table rarefy` method.

It appears that with tables containing very large numbers (~1.0 E10), an error occurs:

Plugin error from feature-table:

```
jsfjt9x_s07y21c0000gn/T/qiime2-q2cli-err-jidby8xt.log
Traceback (most recent call last):
  File "/Users/rhmills/miniconda3/envs/qiime2-2018.4/lib/python3.5/site-packages/q2cli/commands.py", line 274, in __call__
    results = action(**arguments)
  File "<decorator-gen-232>", line 2, in rarefy
  File "/Users/rhmills/miniconda3/envs/qiime2-2018.4/lib/python3.5/site-packages/qiime2/sdk/action.py", line 231, in bound_callable
    output_types, provenance)
  File "/Users/rhmills/miniconda3/envs/qiime2-2018.4/lib/python3.5/site-packages/qiime2/sdk/action.py", line 366, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/Users/rhmills/miniconda3/envs/qiime2-2018.4/lib/python3.5/site-packages/q2_feature_table/_normalize.py", line 13, in rarefy
    table = table.subsample(sampling_depth, axis='sample', by_id=False)
  File "/Users/rhmills/miniconda3/envs/qiime2-2018.4/lib/python3.5/site-packages/biom_format-2.1.6-py3.5-macosx-10.7-x86_64.egg/biom/table.py", line 2693, in subsample
    _subsample(data, n)
  File "biom/_subsample.pyx", line 56, in biom._subsample._subsample (biom/_subsample.c:2079)
  File "/Users/rhmills/miniconda3/envs/qiime2-2018.4/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 398, in repeat
    return _wrapfunc(a, 'repeat', repeats, axis=axis)
  File "/Users/rhmills/miniconda3/envs/qiime2-2018.4/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: count < 0
```

It appears that using a workaround of dividing all values by 10,000 fixes this issue.

**Comment by wasade** [comment]
That looks like an integer overflow. From a check of the code, the value used for repeat is forced to be int32, which would cap it at 2**31. We could tentatively switch this to int64, but I think instead you most likely want to perform subsampling with replacement here (which is part of BIOM 2.1.7) in particular as the expense of the subsampling without replacement is very high.

I do recommend updating QIIME 2 as that version is out of date. The newer version will bring with it the newer version of BIOM too.
