### ISSUE TITLE
BUG: inconsistent order of evaluation for table error checks

### ISSUE THREAD

**Issue by wasade** [biocore/biom-format#813]
An example of the bug is below. If print statements are added into `ErrorProfile.test`, it can be shown that there is an unstable order of evaluation. The reason the second example below works is that `empty` is by default set to `ignore` and not to `raise`. However, `empty` does not presently assert a lack of axis IDs or metadata which is surprising.

```python
$ python
Python 3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import biom
>>> t = biom.Table([], [], ['foo', 'bar'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dtmcdonald/ResearchWork/software/biom-format/biom/table.py", line 508, in __init__
    errcheck(self)
  File "/Users/dtmcdonald/ResearchWork/software/biom-format/biom/err.py", line 472, in errcheck
    raise ret
biom.exception.TableException: Number of sample IDs differs from matrix size!
>>>
$ python
Python 3.5.5 | packaged by conda-forge | (default, Apr  6 2018, 13:43:56)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import biom
>>> t = biom.Table([], [], ['foo', 'bar'])
>>>
```

Issue first observed in biocore/unifrac#65 by @gwarmstrong

**Comment by wasade** [comment]
Fixed in #814
