### ISSUE TITLE
improve error or support empty tsv files

### ISSUE THREAD

**Issue by antgonza** [biocore/biom-format#854]
The current error is not clear of what's the issue so IMOO either raising an error that is clearer or supporting an empty table should be fine; to reproduce
```bash
# this works cause it's _not_ an empty table
$ echo -e '#FeatureID\tSample1\nx\t1' > example.tsv
$ python -c 'import biom; biom.load_table("example.tsv")'

# this doesn't work
$ echo -e '#FeatureID\tSample1' > example.tsv
$ python -c 'import biom; biom.load_table("example.tsv")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/qiita/miniconda3/envs/qp-woltka/lib/python3.8/site-packages/biom/parse.py", line 672, in load_table
    table = parse_biom_table(fp)
  File "/home/qiita/miniconda3/envs/qp-woltka/lib/python3.8/site-packages/biom/parse.py", line 416, in parse_biom_table
    t = Table.from_tsv(file_obj, None, None, lambda x: x)
  File "/home/qiita/miniconda3/envs/qp-woltka/lib/python3.8/site-packages/biom/table.py", line 4875, in from_tsv
    t_md_name) = Table._extract_data_from_tsv(lines, **kwargs)
  File "/home/qiita/miniconda3/envs/qp-woltka/lib/python3.8/site-packages/biom/table.py", line 4975, in _extract_data_from_tsv
    for index in range(0, data_start):
UnboundLocalError: local variable 'data_start' referenced before assignment
```

**Comment by wasade** [comment]
This would be technically supportable:

```python
>>> import biom
>>> biom.Table([], [], ['a', 'b'])
0 x 0 <class 'biom.table.Table'> with 0 nonzero entries (0% dense)
```
