### ISSUE TITLE
conda install biom-format PackagesNotFoundError

### ISSUE THREAD

**Issue by jindongmin** [biocore/biom-format#869]
Hi, 
I'm trying to install biom-format using conda and kept getting this error. 
```bash
(biom_format) dongminjin@10-21-159-247 ~ % conda install biom-format -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - biom-format

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
I'm curious why biom-format cannot be found. I also tried pip install and that worked.

**Comment by wasade** [comment]
It might be in bioconda? I cant recall at the moment

**Comment by jindongmin** [comment]
I tried bioconda too but the error is the same. 

```bash
(biom_format) dongminjin@10-21-159-247 ~ % conda install -c bioconda biom-format
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - biom-format

Current channels:

  - https://conda.anaconda.org/bioconda/osx-arm64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(biom_format) dongminjin@10-21-159-247 ~ % conda install -c bioconda/label/cf201901 biom-format
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - biom-format

Current channels:

  - https://conda.anaconda.org/bioconda/label/cf201901/osx-arm64
  - https://conda.anaconda.org/bioconda/label/cf201901/noarch
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(biom_format) dongminjin@10-21-159-247 ~ % 
```

**Comment by wasade** [comment]
What OS are you? It is in conda-forge:

```bash
$ conda search -c conda-forge biom-format
Loading channels: done
# Name                       Version           Build  Channel             
biom-format                    2.1.6  py27h7eb728f_0  conda-forge         
biom-format                    2.1.6  py35h7eb728f_0  conda-forge         
biom-format                    2.1.6  py36h7eb728f_0  conda-forge         
biom-format                    2.1.7 py27h3b54f70_1002  conda-forge         
biom-format                    2.1.7  py27h7eb728f_0  conda-forge         
biom-format                    2.1.7  py27h7eb728f_1  conda-forge         
biom-format                    2.1.7  py27h7eb728f_2  conda-forge         
biom-format                    2.1.7 py27h917ab60_1001  conda-forge         
biom-format                    2.1.7 py27h917ab60_1002  conda-forge         
biom-format                    2.1.7  py35h7eb728f_0  conda-forge         
biom-format                    2.1.7 py36h3b54f70_1002  conda-forge         
biom-format                    2.1.7  py36h7eb728f_0  conda-forge         
biom-format                    2.1.7  py36h7eb728f_1  conda-forge         
biom-format                    2.1.7  py36h7eb728f_2  conda-forge         
biom-format                    2.1.7 py36h917ab60_1001  conda-forge         
biom-format                    2.1.7 py36h917ab60_1002  conda-forge         
biom-format                    2.1.7 py37h3b54f70_1002  conda-forge         
biom-format                    2.1.7  py37h7eb728f_2  conda-forge         
biom-format                    2.1.7 py37h917ab60_1002  conda-forge         
biom-format                    2.1.7 py38h3b54f70_1002  conda-forge         
biom-format                    2.1.8  py36h3b54f70_0  conda-forge         
biom-format                    2.1.8  py36h642477c_1  conda-forge         
biom-format                    2.1.8  py37h3b54f70_0  conda-forge         
biom-format                    2.1.8  py37h7ff7679_1  conda-forge         
biom-format                    2.1.8  py38h3b54f70_0  conda-forge         
biom-format                    2.1.8  py38hf3d72b9_1  conda-forge         
biom-format                    2.1.8  py39hbaf7cf3_1  conda-forge         
biom-format                    2.1.9  py36h642477c_0  conda-forge         
biom-format                    2.1.9  py37h7ff7679_0  conda-forge         
biom-format                    2.1.9  py38hf3d72b9_0  conda-forge         
biom-format                    2.1.9  py39hbaf7cf3_0  conda-forge         
biom-format                   2.1.10 py310h81f86ea_1  conda-forge         
biom-format                   2.1.10  py36hb29be1e_0  conda-forge         
biom-format                   2.1.10  py37h032687b_1  conda-forge         
biom-format                   2.1.10  py37h8ba3199_0  conda-forge         
biom-format                   2.1.10  py38hbe852b5_1  conda-forge         
biom-format                   2.1.10  py38hfb243c8_0  conda-forge         
biom-format                   2.1.10  py39hc89836e_1  conda-forge         
biom-format                   2.1.10  py39hf24ec92_0  conda-forge  
```

**Comment by jindongmin** [comment]
It's macOS Monterey version12.2.1
```bash
(biom_format) dongminjin@10-21-159-247 ~ % conda install -c conda-forge biom-format
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - biom-format

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I tried conda-forge and still cannot found it.

**Comment by wasade** [comment]
I just ran `$ conda create -n example -c conda-forge biom-format` and it worked for me

Do you have a M1 chip? 

If pip works, I hope that solves your immediate needs. I am confused why conda-forge isn't working for you though. We do rely on pre-compiled libraries in conda, so it's plausible there is something about your target architecture we aren't building for

**Comment by jindongmin** [comment]
Yes, I have a M1 chip. 
I agree that's probably the reason why. Thanks anyway!

**Comment by wasade** [comment]
Ah, okay. We haven't investigated what it will take to port this package to M1 yet. In part, I don't have access to a machine with M1 :) 

If you have a moment, would it be possible to run the unit tests on the pip install version? You can clone the repo (`git clone https://github.com/biocore/biom-format.git`), then switch to the directory, and run `pytest`. You probably need to pip or conda install pytest.

Thank you for the report though, this is very helpful!! It highlights that (a) it seems likely that M1 is fine for biom given pip install seems to work and (b) that we need to revise our builds in conda-forge to reflect M1 architecture

**Comment by jindongmin** [comment]
sure! 
Here's what it looks like
```bash
(biom_format) dongminjin@10-21-159-247 biom-format % pwd              
/Users/dongminjin/biom-format
(biom_format) dongminjin@10-21-159-247 biom-format % pytest
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov=biom
  inifile: /Users/dongminjin/biom-format/pytest.ini
  rootdir: /Users/dongminjin/biom-format
```
I don't think pytest worked? I'm not sure why that is.

**Comment by wasade** [comment]
Weird. Okay. If you're up to it, it should be possible to cd to the tests
dir and execute the files individually but i would understand if you'd like
to limit investigation

**Comment by jindongmin** [comment]
Okay, they all gave the same error.
```bash
(biom_format) dongminjin@10-21-159-247 tests % python test_table.py 
/Users/dongminjin/biom-format/biom/tests/test_table.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as pdt
Traceback (most recent call last):
  File "/Users/dongminjin/biom-format/biom/tests/test_table.py", line 23, in <module>
    from biom import example_table, load_table, concat
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/table.py", line 185, in <module>
    from collections import defaultdict, Hashable, Iterable
ImportError: cannot import name 'Hashable' from 'collections' (/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/collections/__init__.py)
(biom_format) dongminjin@10-21-159-247 tests % python test_parse.py
Traceback (most recent call last):
  File "/Users/dongminjin/biom-format/biom/tests/test_parse.py", line 20, in <module>
    from biom.parse import (generatedby, MetadataMap, parse_biom_table, parse_uc,
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/table.py", line 185, in <module>
    from collections import defaultdict, Hashable, Iterable
ImportError: cannot import name 'Hashable' from 'collections' (/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/collections/__init__.py)
(biom_format) dongminjin@10-21-159-247 tests % python test_util.py
Traceback (most recent call last):
  File "/Users/dongminjin/biom-format/biom/tests/test_util.py", line 19, in <module>
    from biom.table import Table
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/table.py", line 185, in <module>
    from collections import defaultdict, Hashable, Iterable
ImportError: cannot import name 'Hashable' from 'collections' (/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/collections/__init__.py)
(biom_format) dongminjin@10-21-159-247 tests % python test_err.py
Traceback (most recent call last):
  File "/Users/dongminjin/biom-format/biom/tests/test_err.py", line 16, in <module>
    from biom import example_table, Table
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/__init__.py", line 51, in <module>
    from .table import Table
  File "/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/site-packages/biom/table.py", line 185, in <module>
    from collections import defaultdict, Hashable, Iterable
ImportError: cannot import name 'Hashable' from 'collections' (/Users/dongminjin/.pyenv/versions/miniforge3-4.9.2/envs/biom_format/lib/python3.10/collections/__init__.py)

```

**Comment by wasade** [comment]
Thanks. Looks like we are incompatible with python=3.10... fun.

**Comment by wasade** [comment]
These imports were resolved in #865
